# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^.*demographic\.000000$
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb", "500"]
        exclude: ^.*yarn-.*cjs$

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--profile", "black"]

      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["-l", "127"]

      - id: flake8-strict
        name: flake8 (strict)
        entry: flake8
        language: system
        types: [python]
        args: [
          "--count",
          "--select=E9,F63,F7,F82",
          "--show-source",
          "--statistics",
        ]
        files: ^tdwii_plus_examples/.*\.py$

      - id: flake8-relaxed
        name: flake8 (relaxed)
        entry: flake8
        language: system
        types: [python]
        args: [
          "--count",
          "--extend-ignore=E203",
          "--max-line-length=127",
          "--statistics",
        ]
        files: ^tdwii_plus_examples/.*\.py$
        exclude: ^tdwii_plus_examples/(tdd/ui_tdd\.py|rtbdi_creator/ui_form\.py|TDWII_PPVS_subscriber/ui_tdwii_ppvs_subscriber\.py)$

  # Keep this as a repo hook since it's specific to the pre-commit framework
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.2.0
    hooks:
      - id: sync_with_poetry
        args: []
